### ISSUE TITLE
Suggestions for final project output (Visuals,Graphs,Dashboards...)

### ISSUE THREAD

**Issue by SageKai10** [professor-greebie/SENG8080-3-field_project#110]
We need to decide how we will present the data and what the final project will contain.
We can use visuals , graphs, dashboards or prepare research documentation containing our findings.
Need to decide various possibilities to determine final project target.

**Comment by kalesh37** [comment]
Absolutely, I agree with you! It's crucial for us to decide on the best way to present the data and determine the final project target. I think using a combination of visuals, graphs, and dashboards would be a great approach to make the data more accessible and visually appealing. It will help us convey the key insights effectively.

Additionally, preparing research documentation containing our findings would provide a comprehensive understanding of the data and the methodologies we used. This documentation will be valuable for reference and for sharing our research process with others.

To make a well-informed decision, we should explore various possibilities and consider factors such as the project's goals, target audience, and the nature of the data. Let's discuss these options in detail and brainstorm ideas to determine the best approach that aligns with our objectives. Collaboration and feedback from the team will be crucial in shaping the final project.

**Comment by professor-greebie** [comment]
Take a look at nbviewer https://nbviewer.org/. It is a way to launch Jupyter notebooks to a server.
