### ISSUE TITLE
Explore and decide DevOps data pipeline

### ISSUE THREAD

**Issue by jaldip9187** [professor-greebie/SENG8080-3-field_project#116]

**Comment by Divyang01** [comment]
I suggest using PostgreSQL to load this from S3 using ETL pipeline, as the tsv/csv files appears in a structured format; any recommendation?

**Comment by jaldip9187** [comment]
Okay, then we can upload TSV/CSV files on Amazon s3, get data from s3, and store it in Postgres.

**Comment by Nisarg-3428** [comment]
Looks, good to me.

**Comment by shashi2855** [comment]
LGTM
