### ISSUE TITLE
Data Cleaning of the dataset

### ISSUE THREAD

**Issue by Ashish8128** [professor-greebie/SENG8080-3-field_project#117]
I saw the Dataset and had one question, do we need to clean the data or its done already?

**Comment by jaldip9187** [comment]
It is the responsibility of the data cleaning team. Make sure we have a data cleansing team first, and if so, add them as Assignees.

**Comment by svitolopes** [comment]
The Data Quality group is responsible for cleaning the data.

**Comment by varunbansal313** [comment]
We should get an Estimation from the team and also parallelly start on creating the draft on analysis.

**Comment by varunbansal313** [comment]
I see there are 53 columns in the dataset, I think it will make more sense if we drop at least half the columns and then analyze the data, given the time constraint.

![image](https://github.com/professor-greebie/SENG8080-3-field_project/assets/97469778/af6e04b6-ac4d-42c7-af2a-97a5881befc1)

**Comment by AniketTiwari19** [comment]
Yes @varunbansal313 is right we need an Estimation so we can start our work too. 
Data Quality team please do let us know what's your progress. 
Thank you.

**Comment by Ashish8128** [comment]
Does anyone know someone from the data quality team?
If you know someone from data quality team then please assign them in this issue.

**Comment by varunbansal313** [comment]
As per today's discussion with Prof, the data analysis team can own the data quality(as the data quality team is not responding)

**Comment by DelnaMathew** [comment]
Is anyone currently working on this issue? If yes, kindly share the document for collaborative efforts to proceed further.

**Comment by varunbansal313** [comment]
I am working on this, will share later this evening.

**Comment by svitolopes** [comment]
Hey guys,

**Data Quality team**
Manjeet7805 -Manjeet kaur, chahal
Michalle- Malcolm - Michalle ,Malcolm
Mhalakshami Muniraj

**Comment by svitolopes** [comment]
I'm closing this as the Data Quality team opened issue #142.
