### ISSUE TITLE
Getting to know each team member

### ISSUE THREAD

**Issue by jaldip9187** [professor-greebie/SENG8080-3-field_project#118]
Can anyone from each team comment their team members names? So everyone knows who is responsible for the task.

**Comment by professor-greebie** [comment]
Please include name, group and username.  Thank you!

**Comment by ThakkarRajan** [comment]
Data Collection : 
Username: ThakkarRajan
Name: Rajan Thakkar

**Comment by svitolopes** [comment]
**Data Analysis and Visualization**
AniketTiwari19	-	Aniket Kapildev, Tiwari
Ashish8128	 	-	Ashish, Gupta
DelnaMathew	 	-	Delna, Mathew
dhruvi-249	 	-	Dhruvi Bhaskar, Kansara
maulikpatel30	        -	Maulik Niralkumar, Patel
svitolopes	 	-	Simone, Vito Lopes
varunbansal313	-	Varun, Bansal

**Comment by svitolopes** [comment]
Hi @ThakkarRajan, are you alone in the data collection group?

**Comment by ThakkarRajan** [comment]
There are Maybe 6-7 people once they will see the issue they will update their name in my comment till that you can contact me for any issues regarding data collection.

Thank you

**Comment by ReverseN00B** [comment]
Data Research 
@ReverseN00B -Bhavik Mistry
@msaifu - Saifullah, Mohammed
@Arjuna-Sapkota - Sapkota, Arjun
@SaiTiru - Voona, Sai Tirupati
@Nisarg-3428 - Patel, Nisarg Vipulbhai
(can find username) - Pandit, Kaivalya Kartikey

**Comment by msaifu** [comment]
My name is correct.

**Comment by Manjeet7805** [comment]
Data Quality 
Manjeet7805 -Manjeet kaur, chahal
Michalle- Malcolm - Michalle ,Malcolm
Mhalakshami Muniraj

**Comment by DelnaMathew** [comment]
Documentation

@prithviconestoga - Ashok, Prithvi

**Comment by DelnaMathew** [comment]
We have updated the names of each team member along with their respective groups and have created a document, which is uploaded into the documentation folder. With this, we consider the issue closed
