### ISSUE TITLE
Create the documentation.

### ISSUE THREAD

**Issue by svitolopes** [professor-greebie/SENG8080-3-field_project#120]
@dhruvi-249, please create the folder so we can start with the documentation.

**Comment by DelnaMathew** [comment]
@svitolopes @dhruvi-249 We have already created a folder for our team named 'Data Analysis and Visualization.' I believe we can utilize this folder for uploading documentation.

**Comment by svitolopes** [comment]
Hi @DelnaMathew, the documentation we discuss here is for the whole project, not just our group part.

**Comment by ReverseN00B** [comment]
I agree with @DelnaMathew . We already have the GroupWise folders. lets just create a document in each folder enlisting all the members in that group. So we know who is responsible for that group. Those groups who don't have a folder can create one for the document as well as their contributions in the repo.

**Comment by dhruvi-249** [comment]
Hello Team! I made a folder for documentation. @svitolopes have added an introduction and made other changes. People from our team can collaborate with other teams to get information regarding their tasks done to contribute to the documentation.
