### ISSUE TITLE
Explanation about the dataset columns.

### ISSUE THREAD

**Issue by svitolopes** [professor-greebie/SENG8080-3-field_project#137]
Hey guys,

I took time to explain each column in the dataset, hoping it would be helpful for our documentation, data quality, and data visualization group. Please take a look and let me know if it makes sense. Your feedback will help us better understand the data for our project.

Thanks for checking it out!
Simone

[Basic explanation for each column in the dataset.docx](https://github.com/professor-greebie/SENG8080-3-field_project/files/12165307/Basic.explanation.for.each.column.in.the.dataset.docx)

**Comment by ThakkarRajan** [comment]
LGTM

**Comment by RaulOlivaO** [comment]
lgtm!

**Comment by Kranthi-566** [comment]
LGTM!

**Comment by svitolopes** [comment]
Thanks, guys. I'll add it to the documentation.
