### ISSUE TITLE
Data Cleaning

### ISSUE THREAD

**Issue by Maha-Ramya** [professor-greebie/SENG8080-3-field_project#142]
Hi team,
   We are still cleaning the data as data involves more records and we still want to analyze the data deeply to give good quality.
We will keep posted about the updates shortly.

**Comment by Manjeet7805** [comment]
data cleaning#117

**Comment by dhruvi-249** [comment]
Hey! We need to know about the status of data cleaning so we can plan our part of the work. I think the data is still not cleaned so I am reopening this issue until a new dataset is provided.

**Comment by Michelle-Malcolm** [comment]
Status: Cleaned data uploaded yesterday. Hence, closing.  #117
