### ISSUE TITLE
Re-work on KPIs

### ISSUE THREAD

**Issue by DelnaMathew** [professor-greebie/SENG8080-3-field_project#143]
Continuing with the data visualization phase, we've realized that the current dataset might not suffice to address the previously discussed issues and KPIs. Therefore, @svitolopes created a list of questions that we can potentially answer using this dataset. However, we need to assess whether the cleaned dataset will allow us to address these questions and then decide which ones to prioritize.

**Comment by svitolopes** [comment]
Moving on with the data visualization part, and thinking that with this dataset, we will not be able to continue with the issues and KPIs we discussed before. I created this list of questions that we can answer using the dataset, we will need to evaluate if, with the cleaned dataset we will continue to be able to answer these questions and choose which ones we will use.

1. How many individuals were included in the study?
2. What is the age distribution of patients in the dataset?
3. What are the different cancer types present in the dataset, and how many samples are available for each type?
4. What are the detailed subtypes for each cancer type?
5. What is the distribution of patients based on race and sex?
6. What are the different types of chemotherapy treatments used in the study?
7. How many patients received cytotoxic chemotherapy treatment?
8. What is the distribution of patients based on their smoking status?
9. How long was the time from diagnosis to the start of treatment for each patient?
10. What is the status of treatment for the patients?
11. How many patients received radiation therapy as part of their treatment?
12. What are the clonal hematopoiesis mutations identified in the blood samples?
13. How many patients had clonal hematopoiesis mutations?
14. Are there any correlations between the presence of clonal hematopoiesis mutations and specific cancer types?
15. How does the distribution of chemotherapy treatments differ among cancer types?
16. Is there any correlation between patient age and cancer type?
17. How many samples were analyzed per patient on average?
18. Are there any differences in treatment patterns based on the cancer type?

**Comment by Maha-Ramya** [comment]
The above questions can be clarified from Data collection team.

I would like to add few points from Data Quality Group by keeping the below listed considerations.
As for visualization part, you can combine any therapy columns to predict cancer. To my knowledge, I have listed few columns to be considered for visualization part.

The importance of columns for cancer prediction
1. Age: Age is an important factor in cancer risk and prognosis as certain types of cancer are more prevalent in specific age groups.

2. Cancer Type: The general type or category of cancer can significantly impact treatment decisions and patient outcomes.

3. Mutation Count: The number of mutations in the patient's tumor can provide insights into tumor biology and potential treatment options.

4. Race: Race can be relevant in some cancer types as certain ethnic groups may have higher or lower risk factors.

5. Sex: Gender-specific factors can influence cancer risk and treatment responses.

6. Smoking Status: Smoking is a well-known risk factor for many types of cancer.

7. Tumor Mutational Burden (TMB): TMB is a measure of the number of mutations in the tumor and can be indicative of a patient's response to immunotherapy.

8. Cumulative Exposure to Targeted Therapy: The total or cumulative amount of targeted therapy treatment the patient received during the study period.

9. Targeted Therapy Treatment: Information about targeted therapy treatment can be critical for personalized treatment decisions.

10. Radiation Therapy: The use of radiation therapy is essential information for predicting treatment outcomes.

11. Immunotherapy Treatment: Immunotherapy has become a significant treatment option for certain cancers, and its use can be crucial for prediction models.

**Comment by svitolopes** [comment]
Sorry, @Maha-Ramya 

The questions here are for us in the visualization group to use as a reference for creating the dashboard. We are waiting for the clean dataset to understand which questions we will be able to use. You don't need to answer these questions.

Thank you

**Comment by varunbansal313** [comment]
Some of the KPI's are already answered in the code in uploaded. Please review the file and make/add the necessary changes. If any questions, please let me know.

**Comment by svitolopes** [comment]
As we decided to work with Tableau, I suggest we choose some questions and divide the activities among the group members (developing the charts and creating the dashboard) so that we all participate in the final result.
We need to use the data set released by the data quality group and also understand with the DevOps team if they will add the clean dataset on Postgres.

**Comment by svitolopes** [comment]
I cleaned up the questions to make our decision easier. @varunbansal313 already answers some in his file. 

1.	How many individuals were included in the study?
2.	What is the age distribution of patients in the dataset? **(Exist on Varun file)**
3.	What are the different cancer types in the dataset, and how many samples are available for each type? **(Exist on Varun file)**
4.	What is the distribution of patients based on race and sex? **(Exist on Varun file separated)**
5.	What are the different types of chemotherapy treatments used in the study?
6.	What is the distribution of patients based on their smoking status? **(Exist on Varun file - Age distribution by smoking status)**
7.	What is the status of treatment for the patients?
8.	How many patients received radiation therapy as part of their treatment?
9.	Are there any correlations between mutations and specific cancer types?
10.	Is there any correlation between patient age and cancer type? **(Exist on Varun file)**

If everyone agrees, we can define how the dashboard will be and how we will make everyone participate in the creation.

**Comment by Ashish8128** [comment]
@svitolopes Yes Lets discuss on creation of the dashboard and also I'm going through the data to see if we can answer some more questions apart from those you mentioned above.

**Comment by DelnaMathew** [comment]
We can currently solidify the following KPIs for implementation, all of which have already been done by @varunbansal313.

1.	What is the age distribution of patients in the dataset? 
2.	What are the different cancer types in the dataset, and how many samples are available for each type? 
3.	What is the distribution of patients based on race and sex? 
4.	What is the distribution of patients based on their smoking status? 
5.	Is there any correlation between patient age and cancer type?
