### ISSUE TITLE
Provide a Brief on the Research approach to analysis and data collection

### ISSUE THREAD

**Issue by sujaymacwan** [professor-greebie/SENG8080-3-field_project#38]
More information is needed in regard to the dataset.

**Comment by professor-greebie** [comment]
Thanks Sujay. For issues, it's much better to include a descriptive phrase or sentence in the title. This will make it easy for us to find this issue and eventually mark it as resolved.

**Comment by SageKai10** [comment]
Created a proposal markdown file for given task.
Kindly update and add changes to file regarding the research approach.
