### ISSUE TITLE
Provide some details on the GFF/GTF format

### ISSUE THREAD

**Issue by professor-greebie** [professor-greebie/SENG8080-3-field_project#73]
Please include the following:
- [x] A url to the initial file for ingestion into the data warehouse.
- [x] Any resources in python to parse the file.
- [x] Any links or resources to help us understand how we will deal with the data.

**Comment by msaifu** [comment]
Added readme.md under the Research folder with details.

**Comment by msaifu** [comment]
Added readme.md under the Research folder with details.
