### ISSUE TITLE
Recommendation About Profile

### ISSUE THREAD

**Issue by ThakkarRajan** [professor-greebie/SENG8080-3-field_project#90]
Hello, 
If possible, then all contributors mention your group name in your BIO.
Thank You :)

**Comment by RaulOlivaO** [comment]
Done!

**Comment by sujaymacwan** [comment]
Done!

**Comment by jaldip9187** [comment]
Done from DevOps

**Comment by ThakkarRajan** [comment]
Thank You for considering my idea.
Regards,
Rajan Thakkar.
