### ISSUE TITLE
Research what questions we can answer and what KPIs to use on human genome data.

### ISSUE THREAD

**Issue by svitolopes** [professor-greebie/SENG8080-3-field_project#97]
We need to prepare some questions and identify the main KPIs used in the Human Genome area to answer them using the dashboard.

**Comment by svitolopes** [comment]
Ashish assigned.

**Comment by AniketTiwari19** [comment]
Hi @svitolopes , I did some research on this topic 
I can either e-mail you or I can attach the document here.

**Comment by varunbansal313** [comment]
Hi Aniket,
You can attach the doc here, I can help review the doc and suggest/add changes.

**Comment by AniketTiwari19** [comment]
[Research.docx](https://github.com/professor-greebie/SENG8080-3-field_project/files/11791076/Research.docx)

**Comment by svitolopes** [comment]
Nice Aniket
Maybe, we need to put this file inside the research folder with the name of the KPIs, for example, and the changes must be made via pull request. Thus, the teacher can see the contributions.
Does anyone know how to do this?

**Comment by maulikpatel30** [comment]
> [Research.docx](https://github.com/professor-greebie/SENG8080-3-field_project/files/11791076/Research.docx)

I suggest one more question under:   
5. Gene Expression and Regulation: 
How do epigenetic modifications influence gene expression and regulation?

**Comment by maulikpatel30** [comment]
What do you guys think?

**Comment by Ashish8128** [comment]
Also we can add the below question in 1. Genetic Variation.
How does genetic diversity vary across different geographical regions?

**Comment by DelnaMathew** [comment]
We can add one question as part of Ancestry and Population Genetics:

How can genetic data be used to investigate population migrations and uncover historical relationships among different populations?

**Comment by dhruvi-249** [comment]
Hello everyone! I have made an updated document along with everyone's questions and mine added as well under the following sections - Disease Susceptibility and Pharmacogenomics. Let's ask the professor tomorrow on how further we need to put this file into our main branch. 
[Research.docx](https://github.com/professor-greebie/SENG8080-3-field_project/files/11828637/Research.docx)

**Comment by DelnaMathew** [comment]
Created a new folder 'data analysis and visualization' in the main branch and uploaded the above document with a new name 'Discussion on KPI'.
